# Import Libaries

In [10]:
import numpy as np
import pandas as pd

# Importing Data

In [11]:
crop = pd.read_csv("Crop_recommendation.csv")
crop.head()

N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

# Asq Six Question to yourself

In [12]:
crop.shape

(2100, 8)

In [13]:
crop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2100 entries, 0 to 2099
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   N            2100 non-null   int64  
 1   P            2100 non-null   int64  
 2   K            2100 non-null   int64  
 3   temperature  2100 non-null   float64
 4   humidity     2100 non-null   float64
 5   ph           2100 non-null   float64
 6   rainfall     2100 non-null   float64
 7   label        2100 non-null   object 
dtypes: float64(4), int64(3), object(1)
memory usage: 131.4+ KB


In [14]:
crop.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [15]:
crop.duplicated().sum()

0

In [16]:
crop.describe()

N            P            K  temperature     humidity  \
count  2100.000000  2100.000000  2100.000000  2100.000000  2100.000000   
mean     51.855238    49.592857    40.912857    25.700371    70.986853   
std      37.189995    28.711614    39.171220     4.715312    22.667937   
min       0.000000     5.000000     5.000000    10.010813    14.258040   
25%      22.000000    27.000000    20.000000    22.954330    59.237124   
50%      38.000000    49.000000    30.000000    25.628159    80.000686   
75%      86.000000    65.000000    47.000000    28.511034    90.194600   
max     140.000000   145.000000   205.000000    43.675493    99.981876   

                ph     rainfall  
count  2100.000000  2100.000000  
mean      6.490601   105.075647  
std       0.783263    55.737933  
min       3.504752    20.211267  
25%       6.000794    63.489314  
50%       6.451753    97.659622  
75%       6.945725   130.140535  
max       9.935091   298.560117

In [17]:
crop['label'].value_counts()

label
rice           100
mango          100
jute           100
cotton         100
coconut        100
papaya         100
orange         100
apple          100
muskmelon      100
watermelon     100
banana         100
maize          100
pomegranate    100
lentil         100
blackgram      100
mungbean       100
mothbeans      100
pigeonpeas     100
kidneybeans    100
chickpea       100
coffee         100
Name: count, dtype: int64

# Encoding

In [18]:
crop_dict = {
    'rice': 1,
    'maize': 2,
    'jute': 3,
    'cotton': 4,
    'coconut': 5,
    'papaya': 6,
    'orange': 7,
    'apple': 8,
    'muskmelon': 9,
    'watermelon': 10,
    'mango': 11,
    'banana': 12,
    'pomegranate': 13,
    'lentil': 14,
    'blackgram': 15,
    'mungbean': 16,
    'mothbeans': 17,
    'pigeonpeas': 18,
    'kidneybeans': 19,
    'chickpea': 20,
    'coffee': 21
}
crop['crop_num']=  crop['label'].map(crop_dict)

In [19]:
crop

N   P   K  temperature   humidity        ph    rainfall   label  \
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice   
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice   
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice   
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice   
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice   
...   ...  ..  ..          ...        ...       ...         ...     ...   
2095  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee   
2096   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee   
2097  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee   
2098  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee   
2099  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee   

      crop_num  
0            1  
1            1  
2            1  
3            1  
4            1  
...        ...  
2095        21  
2096        21  
2097        21  
2098        21  
2099        21  

[2100 rows x 9 columns]

In [20]:
crop.drop(['label'],axis=1,inplace=True)
crop.head()

N   P   K  temperature   humidity        ph    rainfall  crop_num
0  90  42  43    20.879744  82.002744  6.502985  202.935536         1
1  85  58  41    21.770462  80.319644  7.038096  226.655537         1
2  60  55  44    23.004459  82.320763  7.840207  263.964248         1
3  74  35  40    26.491096  80.158363  6.980401  242.864034         1
4  78  42  42    20.130175  81.604873  7.628473  262.717340         1

# Train Test Split

In [21]:
X = crop.drop(['crop_num'],axis=1)
y = crop['crop_num']

In [22]:
X

N   P   K  temperature   humidity        ph    rainfall
0      90  42  43    20.879744  82.002744  6.502985  202.935536
1      85  58  41    21.770462  80.319644  7.038096  226.655537
2      60  55  44    23.004459  82.320763  7.840207  263.964248
3      74  35  40    26.491096  80.158363  6.980401  242.864034
4      78  42  42    20.130175  81.604873  7.628473  262.717340
...   ...  ..  ..          ...        ...       ...         ...
2095  107  34  32    26.774637  66.413269  6.780064  177.774507
2096   99  15  27    27.417112  56.636362  6.086922  127.924610
2097  118  33  30    24.131797  67.225123  6.362608  173.322839
2098  117  32  34    26.272418  52.127394  6.758793  127.175293
2099  104  18  30    23.603016  60.396475  6.779833  140.937041

[2100 rows x 7 columns]

In [23]:
y

0        1
1        1
2        1
3        1
4        1
        ..
2095    21
2096    21
2097    21
2098    21
2099    21
Name: crop_num, Length: 2100, dtype: int64

In [24]:
y.shape

(2100,)

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [27]:
X_train

N   P   K  temperature   humidity        ph    rainfall
1592   12   8  10    16.148203  91.444803  7.995849  107.428766
829     0  65  24    28.495844  62.446162  7.841496   53.145310
414    27  72  17    28.980394  57.232652  6.347929  120.743566
704    44  58  18    28.036441  65.066017  6.814411   72.495077
755    20  68  17    30.118730  60.116808  6.578715   71.729804
...   ...  ..  ..          ...        ...       ...         ...
1638   44  57  53    42.304958  90.514318  6.931721   74.876786
1095  108  94  47    27.359116  84.546250  6.387431   90.812505
1130   11  36  31    27.920633  51.779659  6.475449  100.258567
1294  119  30  49    25.357947  80.458463  6.903020   47.720782
860    32  78  22    23.970814  62.355576  7.007038   53.409060

[1680 rows x 7 columns]


# Scale the features using MinMaxScaler

In [28]:
from sklearn.preprocessing import MinMaxScaler
ms = MinMaxScaler()

X_train = ms.fit_transform(X_train)
X_test = ms.transform(X_test)

In [29]:
X_train

array([[0.08571429, 0.02142857, 0.025     , ..., 0.90054654, 0.69842306,
        0.31333882],
       [0.        , 0.42857143, 0.095     , ..., 0.56221618, 0.6744192 ,
        0.11831931],
       [0.19285714, 0.47857143, 0.06      , ..., 0.50138957, 0.44215045,
        0.36117375],
       ...,
       [0.07857143, 0.22142857, 0.13      , ..., 0.4377689 , 0.46198144,
        0.28757906],
       [0.85      , 0.17857143, 0.22      , ..., 0.77236769, 0.52847419,
        0.09883107],
       [0.22857143, 0.52142857, 0.085     , ..., 0.5611593 , 0.54465022,
        0.11926686]])

# Training Models

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import ExtraTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score,confusion_matrix

# create instances of all models
models = {
    'Logistic Regression': LogisticRegression(),
    'Naive Bayes': GaussianNB(),
    'Support Vector Machine': SVC(),
    'K-Nearest Neighbors': KNeighborsClassifier(),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Bagging': BaggingClassifier(),
    'AdaBoost': AdaBoostClassifier(),
    'Gradient Boosting': GradientBoostingClassifier(),
    'Extra Trees': ExtraTreeClassifier(),
}


for name, model in models.items():
    model.fit(X_train,y_train)
    ypred = model.predict(X_test)
    
    print(f"{name}  with accuracy : {accuracy_score(y_test,ypred)}")
    print("Confusion matrix : ",confusion_matrix(y_test,ypred))
    print("==========================================================")
    

Logistic Regression  with accuracy : 0.930952380952381
Confusion matrix :  [[18  0  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 16  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  0 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 14  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  1  0  0 11  0  0  0  0  0  1  0  0  0  3  0  0  0  0  0]
 [ 0  0  0  0  0  0 23  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 23  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 27  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 15  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 18  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 16  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 17  1  0  0  0  0  0  0]
 

E:\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


AdaBoost  with accuracy : 0.3738095238095238
Confusion matrix :  [[ 0  0  0  0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 11  0  6  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 14  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 23  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 23  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 27  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 16  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 17  0 

In [31]:
# finally selected randomforest model

rfc = RandomForestClassifier()
rfc.fit(X_train,y_train)
ypred = rfc.predict(X_test)
accuracy_score(y_test,ypred)

0.9880952380952381

In [32]:
# or gausianjb
gnb = GaussianNB()
gnb.fit(X_train,y_train)
ypred = gnb.predict(X_test)
accuracy_score(y_test,ypred)

0.9904761904761905

# Predictive System

In [33]:
def recommendation(N,P,k,temperature,humidity,ph,rainfal):
    features = np.array([[N,P,k,temperature,humidity,ph,rainfal]])
    transformed_features = ms.fit_transform(features)
    prediction = rfc.predict(transformed_features)
    print(prediction)
    return prediction[0] 

In [39]:
# new inputs


N = 40
P = 50
k = 50
temperature = 40.0
humidity = 20
ph = 100
rainfall = 100

predict = recommendation(N,P,k,temperature,humidity,ph,rainfall)

crop_dict = {1: "Rice", 2: "Maize", 3: "Jute", 4: "Cotton", 5: "Coconut", 6: "Papaya", 7: "Orange",
                 8: "Apple", 9: "Muskmelon", 10: "Watermelon", 11: "Mango", 12: "Banana",
                 13: "Pomegranate", 14: "Lentil", 15: "Blackgram", 16: "Mungbean", 17: "Mothbeans",
                 18: "Pigeonpeas", 19: "Kidneybeans", 20: "Chickpea", 21: "Coffee"}

if predict in crop_dict:
    crop = crop_dict[predict]
    print("{} is a best crop to be cultivated ".format(crop))
else:
    print("Sorry are not able to recommend a proper crop for this environment")

[19]
Kidneybeans is a best crop to be cultivated 


In [35]:
# new inputs 2


N = 100
P = 90
k = 100
temperature = 50.0
humidity = 90.0
ph = 100
rainfall = 202.0

predict = recommendation(N,P,k,temperature,humidity,ph,rainfall)

crop_dict = {1: "Rice", 2: "Maize", 3: "Jute", 4: "Cotton", 5: "Coconut", 6: "Papaya", 7: "Orange",
                 8: "Apple", 9: "Muskmelon", 10: "Watermelon", 11: "Grapes", 12: "Mango", 13: "Banana",
                 14: "Pomegranate", 15: "Lentil", 16: "Blackgram", 17: "Mungbean", 18: "Mothbeans",
                 19: "Pigeonpeas", 20: "Kidneybeans", 21: "Chickpea", 22: "Coffee"}

if predict in crop_dict:
    crop = crop_dict[predict]
    print("{} is a best crop to be cultivated ".format(crop))
else:
    print("Sorry are not able to recommend a proper crop for this environment")

[19]
Pigeonpeas is a best crop to be cultivated 


In [40]:
# new inputs 2
N = 10
P = 10
k = 10
temperature = 15.0
humidity = 80.0
ph = 4.5
rainfall = 10.0

predict = recommendation(N,P,k,temperature,humidity,ph,rainfall)

crop_dict = {1: "Rice", 2: "Maize", 3: "Jute", 4: "Cotton", 5: "Coconut", 6: "Papaya", 7: "Orange",
                 8: "Apple", 9: "Muskmelon", 10: "Watermelon", 11: "Mango", 12: "Banana",
                 13: "Pomegranate", 14: "Lentil", 15: "Blackgram", 16: "Mungbean", 17: "Mothbeans",
                 18: "Pigeonpeas", 19: "Kidneybeans", 20: "Chickpea", 21: "Coffee"}

if predict in crop_dict:
    crop = crop_dict[predict]
    print("{} is a best crop to be cultivated ".format(crop))
else:
    print("Sorry are not able to recommend a proper crop for this environment")

[19]
Kidneybeans is a best crop to be cultivated 


In [37]:
import pickle
pickle.dump(rfc,open('model.pkl','wb'))
pickle.dump(ms,open('minmaxscaler.pkl','wb'))